### ISSUE TITLE
'oscal' name of the tool causes major confusion with OSCAL schemas.

### ISSUE THREAD

**Issue by iMichaela** [GSA/oscal-js#4]
Calling the tool "oscal" causes major confusion with the well established name of the OSCAL language, in particular for new users going forward.

Please change the name of the package to eliminate confusion. The simple capitalization difference is absolutely not sufficient.

**Comment by wandmagic** [comment]
sure would "oscal-js" for the package name and osc for the binary be sufficient?

**Comment by iMichaela** [comment]
> sure would "oscal-js" for the package name and osc for the binary be sufficient?

Anything that is not "oscal" or "OSCAL" will do it. If you want to be super descriptive, you could call it "OSCAL Interpreter" and abbreviate it as "oi" or "oscalin" , or "OSCAL Processor" and abbreviate it as "oscalproc" or "oproc" or similar... If "osc" stands for something meaningful as "OSCAL Super Cool" tool then that makes sense too.

**Comment by aj-stein-gsa** [comment]
Seeing as [OSCAL the concept, tools, and documentation are in the public domain](https://github.com/usnistgov/OSCAL/blob/4f02dac6f698efda387cc5f55bc99581eaf494b6/LICENSE.md) and there are a variety of community efforts whose website is simply the name oscal and a top-level domain ([oscal.io](https://osca.io); [oscal.club](https://oscal.club)), not to mention the many software packages in multiple ecosystems with simply the name OSCAL I have found.

I do not see the risk for confusion as significant.  I am closing this issue.
