### ISSUE TITLE
README clarification needed

### ISSUE THREAD

**Issue by iMichaela** [GSA/oscal-js#5]
The README file introduces this project as "OSCAL CLI". A description of the relation **(if any**) between 'oscal-cli' developed by NIST and planned to be used by FedRAMP (as publicly announced) and this "OSCAL  CLI" described as providing similar functionality as oscal-cli will help users better understand current project.

**Comment by wandmagic** [comment]
this library uses oscal-cli under the hood, its a wrapper and installer for it, with additional capabilities such as recursive validation and leveraging external metaschema constraints

**Comment by aj-stein-gsa** [comment]
> The README file introduces this project as "OSCAL CLI". A description of the relation **(if any**) between 'oscal-cli' developed by NIST and planned to be used by FedRAMP (as publicly announced) and this "OSCAL CLI" described as providing similar functionality as oscal-cli will help users better understand current project.

If you could propose a change you would like to see to clarify that in the README, we would definitely welcome it. If not, I would like to close the issue. We are always willing to accept issues and pull requests, so if you have something concrete in mind, please propose it. I am sure we would graciously accept such a change.
