### ISSUE TITLE
POAM scaffold `TypeError: Cannot set properties of undefined (setting 'uuid')`

### ISSUE THREAD

**Issue by devbytyler** [GSA/oscal-js#9]
Running the POAM scaffold:

`> oscal scaffold`
`> ? Select the OSCAL template: fedramp-poam`
`> ? Select the OSCAL baseline: HIGH` (seems odd that it is asking me this)
`> ? Use resolved catalog? n`
`> ? Enter the SSP name: This is not an SSP` (seems odd that it is asking me this)
`> ? Enter the output path: ./`

Logs a mostly complete POAM to stdout, but terminates with an error and does not create the file

```bash
file:///Users/[...]/.nvm/versions/node/v18.12.1/lib/node_modules/oscal/dist/scaffold.js:86
    templateJson['system-security-plan'].uuid = uuidv4();

TypeError: Cannot set properties of undefined (setting 'uuid')
    at file:///Users/[...]/.nvm/versions/node/v18.12.1/lib/node_modules/oscal/dist/scaffold.js:86:47
    at Generator.next (<anonymous>)
    at fulfilled (file:///Users/[...]/.nvm/versions/node/v18.12.1/lib/node_modules/oscal/dist/scaffold.js:4:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by wandmagic** [comment]
fixed as of version 1.4.4, re-open if you find an issue

and as for getting the templates to validate track  https://github.com/GSA/fedramp-automation/issues/637 this issue so we can evaluate how we can improve scaffolding so we can get valid results from the scaffold.
